myapp/urls.py
from django.urls import path
from .views import HomePageView


urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

products/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import (get_category_id,
                    category_editpopup,category_createpopup,category_deletepopup,
                    product_create,product_edit,  product_homeview, validate_category,
                    delete_all_products, batch_delete_products,
                    export_products, export_products_batch,
                    ProductReadView, ProductListView, ProductUpdateView)


urlpatterns = [
    path('', product_homeview, name='product-home'),
    path('new/', product_create, name = "product-create"),
    path('<pk>/update/', product_edit, name='product-update'),
    path('read/<pk>/', ProductReadView.as_view(), name='product-read'),

    path('export/csv/', export_products, name='product-export'),
    # path('<id>/export/csv/single', export_products_single, name='product-export-single'),
    path('<str:id>/export/csv/batch', export_products_batch, name='product-export_batch'),

    path('<str:id>/delete', batch_delete_products, name='product-delete-batch'),
    path('delete/', delete_all_products, name='product-delete-all'),

    path('category/create/', category_createpopup, name = "category_create"),
    url(r'^category/(?P<pk>\d+)/edit', category_editpopup, name = "category_edit"),
    url(r'^category/(?P<pk>\d+)/delete', category_deletepopup, name = "category-delete"),
    path('category/ajax/get_category_id', get_category_id, name = "get_category_id"),

    path('<str:id>/validate_category', validate_category, name = "validate_category"),
]

salesforce_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import ProfilePageView

admin.site.site_header = "Salesforce Admin Page"
admin.site.site_title = "Salesforce Management System portal"
admin.site.index_title = "Welcome to Salesforce admin page!"



urlpatterns = [
    path('admin/', admin.site.urls, name='admin-pages'),
    path('profile/<int:pk>', ProfilePageView.as_view(), name='profile'),


    # User management
    path('', include('dashboards.urls')),
    path('dashboard/', include('dashboards.urls')),
    path('accounts/', include('allauth.urls')),
    path('customer/', include('customers.urls')),
    path('distributor/', include('distributors.urls')),
    path('product/', include('products.urls')),
    path('estimate/', include('estimates.urls')),

]

handler404 = 'myapp.views.my_custom_page_not_found_view'
handler500 = 'myapp.views.my_custom_error_view'
handler400 = 'myapp.views.my_custom_bad_request_view'

products/models.py
from django.db import models
from distributors.models import Distributor
from django.contrib.auth import get_user_model
from django.urls import reverse
import datetime
now = datetime.datetime.now()

class Category(models.Model):
    categoryname = models.CharField(max_length=100)

    def __str__(self):
        return self.categoryname

class Product(models.Model):
    productCode = models.CharField(max_length=100, unique=True)
    serialNo = models.CharField(max_length=100, unique=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='product_category')
    description = models.CharField(max_length=100)
    distributor = models.ForeignKey(Distributor, on_delete=models.SET_NULL, null=True, related_name='product_distributor')
    pricePerUnit = models.DecimalField(max_digits=10, decimal_places=2)
    srp = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='product_created')
    last_updated_at = models.DateTimeField(auto_now=True)
    last_updated_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='product_updated')

    class Meta:
        permissions = [
            ('export_product', 'Can export product data as excel file'),
        ]

    def __str__(self):
        return self.productCode

    def get_absolute_url(self):
        return reverse('product-home')

products/forms.py
from bootstrap_modal_forms.forms import BSModalForm
from django.forms import ModelForm
from .models import Product, Category


class ProductForm(ModelForm):
	class Meta:
		model = Product
		fields = [
			"productCode",
    		"serialNo",
			"category",
			"distributor",
			"description",
			"pricePerUnit",
			"srp",
		]

class CategoryForm(ModelForm):
	class Meta:
		model = Category
		fields = [
			"categoryname"
		]

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.csrf import csrf_exempt

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from bootstrap_modal_forms.generic import BSModalReadView,BSModalDeleteView

from products.models import Product, Category
from distributors.models import Distributor
from django.contrib.auth.models import User
from django.db.models import Q

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

from .forms import ProductForm, CategoryForm

import json
import csv
import datetime


class ProductListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Product
    template_name = 'product/product_home.html'
    context_object_name = 'products'
    ordering = ['productCode']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = Product.objects.all()

        return context

    permission_required = 'products.view_product'

@login_required
@permission_required('products.add_product', raise_exception=True)
def product_homeview(request):
    template_name = 'product/product_home.html'
    context = {}
    categoryList = set()
    distributorList = set()

    product = Product.objects.all()

    for prod in product:
        distributorList.add(prod.distributor)

    for prod in product:
        categoryList.add(prod.category)

    context['category_list'] = categoryList
    context['distributor_list'] = distributorList
    context['products'] = product

    return render(request, template_name, context)

def validate_category(request, id):
    template_name = 'product/product_home.html'
    context = {}
    categoryList = set()
    distributorList = set()

    products = Product.objects.all()
    categoryID = Category.objects.get(categoryname=id).pk
    product = Product.objects.filter(category=categoryID)
    print(product)
    for prod in products:
        distributorList.add(prod.distributor)

    for prod in products:
        categoryList.add(prod.category)

    context['category_list'] = categoryList
    context['distributor_list'] = distributorList
    context['products'] = product

    return render(request, template_name, context)

class ProductReadView(LoginRequiredMixin, PermissionRequiredMixin, BSModalReadView):
    model = Product
    context_object_name = 'products'
    template_name = 'product/product_read.html'
    permission_required = 'products.view_product'


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Product
    template_name = 'product/product_update.html'
    form_class = ProductForm
    success_message = '✓ Product was successfully updated'
    success_url = reverse_lazy('product-home')
    permission_required = 'products.edit_product'

    def form_valid(self, form):
        form.instance.last_updated_by = self.request.user
        return super().form_valid(form)

# FUNCTION BASE VIEWS



def product_create(request):
    myform = ProductForm(request.POST or None)
    if request.POST:
        if myform.is_valid():
            instance = myform.save(commit=False)
            instance.created_by = request.user
            instance.last_updated_by = request.user
            instance.save()
            return HttpResponseRedirect("/product/")

    return render(request, "product/product_create.html", {"form": myform, })


def product_edit(request, pk=None):
    context ={}
    obj = get_object_or_404(Product, pk=pk)

    myform = ProductForm(request.POST or None, instance=obj)

    if request.POST:
        if myform.is_valid():
            instance = myform.save(commit=False)
            instance.created_by = request.user
            instance.last_updated_by = request.user
            instance.save()
            return HttpResponseRedirect("/product/")

    context["form"] = myform
    return render(request, "product/product_update.html",context)


def category_createpopup(request):
    form = CategoryForm(request.POST or None)
    if form.is_valid():
        instance = form.save()
        return HttpResponse('<script>opener.closeAddPopup(window, "%s", "%s", "#id_category");</script>' % (instance.pk, instance))

    return render(request, "product/category_form.html", {"form": form})


def category_editpopup(request, pk=None):
    instance = get_object_or_404(Category, pk=pk)
    oldname = instance.categoryname
    form = CategoryForm(request.POST or None, instance=instance)

    if form.is_valid():
        instance = form.save()
        return HttpResponse('<script>opener.closeEditPopup(window, "%s", "%s", "%s", "#id_category");</script>' % (instance.pk, instance, oldname))

    return render(request, "product/category_form.html", {"form": form})


def category_deletepopup(request, pk=None):
    instance = get_object_or_404(Category, pk=pk)
    oldId = instance.pk
    categoryname = instance.categoryname

    if request.method == "POST" and request.user.is_authenticated:
        instance.delete()
        return HttpResponse('<script>opener.closeDeletePopup(window, "%s");</script>' % (oldId))

    return render(request, "product/category_delete.html", {"categoryname": categoryname})


@csrf_exempt
def get_category_id(request):
    if request.is_ajax():
        category_name = request.GET['category_name']
        category_id = Category.objects.get(categoryname=category_name).id
        data = {'category_id': category_id, }
        return HttpResponse(json.dumps(data), content_type='application/json')
    return HttpResponse("/")

# FUNCTION VIEWS FOR EXPORTING TO EXCEL


@login_required
@permission_required('products.export_product', raise_exception=True)
def export_products(request):
    now = datetime.datetime.now()
    response = HttpResponse(content_type='text/csv')
    filename = 'attachment; filename=' + 'Product - ' + \
        now.strftime("%Y-%m-%d | %H.%M.%S") + '.csv'
    response['Content-Disposition'] = filename

    writer = csv.writer(response)
    writer.writerow(['Product Code', 'Serial No', 'Category', 'Description', 'Distributor', 'Price Per Unit', 'SRP'])

    productList = Product.objects.all();
    for product in productList:
        prodCode = Product.objects.values_list('productCode', flat=True).get(pk=product.pk)
        serialNo = Product.objects.values_list('serialNo', flat=True).get(pk=product.pk)
        pricePerUnit = Product.objects.values_list('pricePerUnit', flat=True).get(pk=product.pk)
        description = Product.objects.values_list('description', flat=True).get(pk=product.pk)
        srp = Product.objects.values_list('srp', flat=True).get(pk=product.pk)

        categoryID = Product.objects.values_list('category', flat=True).get(pk=product.pk)
        distriID = Product.objects.values_list('distributor', flat=True).get(pk=product.pk)
        print(type(categoryID))

        if categoryID is None:
            category = "None"
        else:
            category = Category.objects.values_list('categoryname', flat=True).get(pk=categoryID)

        if distriID is None:
            distributor = "None"
        else:
            distributor = Distributor.objects.values_list('distributorName', flat=True).get(pk=distriID)
        products = ([prodCode, serialNo, category, description, distributor, pricePerUnit, srp])
        writer.writerow(products)

    return response

# # Export Single Products
# @login_required
# @permission_required('products.export_product', raise_exception=True)
# def export_products_single(request, id):
#     products = Product.objects.filter(pk=id).values_list('productCode', 'serialNo', 'category', 'description', 'distributor', 'pricePerUnit', 'srp')
#
#     cust = str(products[0][0])
#     now = datetime.datetime.now()
#     response = HttpResponse(content_type='text/csv')
#     filename = 'attachment; filename=' + 'Product - ' + \
#         now.strftime("%Y-%m-%d | %H.%M.%S") + '-' + cust + '.csv'
#     response['Content-Disposition'] = filename
#
#     writer = csv.writer(response)
#     writer.writerow(['Product Code', 'Serial No', 'Category', 'Description', 'Distributor', 'Price Per Unit', 'SRP'])
#
#     for product in products:
#         prodCode = Product.objects.values_list('productCode', flat=True).get(pk=product.pk)
#         serialNo = Product.objects.values_list('serialNo', flat=True).get(pk=product.pk)
#         pricePerUnit = Product.objects.values_list('pricePerUnit', flat=True).get(pk=product.pk)
#         description = Product.objects.values_list('description', flat=True).get(pk=product.pk)
#         srp = Product.objects.values_list('srp', flat=True).get(pk=product.pk)
#
#         categID = Product.objects.values_list('category', flat=True).get(pk=product.pk)
#         distriID = Product.objects.values_list('distributor', flat=True).get(pk=product.pk)
#
#         category = Category.objects.values_list('categoryname', flat=True).get(pk=categID)
#         distributor = Distributor.objects.values_list('distributorName', flat=True).get(pk=distriID)
#         products = ([prodCode, serialNo, category, description, distributor, pricePerUnit, srp])
#         writer.writerow(products)
#
#     return response


@login_required
@permission_required('products.export_product', raise_exception=True)
def export_products_batch(request, id):
    now = datetime.datetime.now()
    response = HttpResponse(content_type='text/csv')
    filename = 'attachment; filename=' + 'Product - Batch -' + \
        now.strftime("%Y-%m-%d | %H.%M.%S") + '.csv'
    response['Content-Disposition'] = filename

    writer = csv.writer(response)

templates/product/category_delete.html
{% extends "product/category_form.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<form method = 'POST' action= '' enctype = "multipart/form-data" novalidate id = "category-form">{% csrf_token %}
	<h4>Delete the category?</h4>
	<ul>
		<li class=" mt-2"><span class="mr-2">&cross;</span>{{ categoryname }}</li>
	</ul>
	<button type="submit" name="button" class="button button-delete"><span>Confirm Delete</span></button>
</form>
{% endblock %}

templates/product/category_form.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Category</title>

	<link rel="stylesheet" href="{% static 'css/base/css-reset.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/base/button.css' %}">
	<link rel="stylesheet" href="{% static 'css/apps/category.css' %}">
</head>
<body>
	<div class="content-container">
		{% block content %}
		<form method = 'POST' enctype = "multipart/form-data" novalidate id = "category-form">{% csrf_token %}
			{{form | crispy}}
			<button type="submit" name="button" class="button"><span>Submit</span></button>
		</form>
		{% endblock %}
	</div>
</body>
</html>

templates/product/product_batch_delete.html
{% extends "_base.html" %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/apps/apps_create_update.css' %}">
{% endblock %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
    {% if perms.customers.is_superuser  %}
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    {% else %}
      <li class="breadcrumb-item">Home</li>
    {% endif %}
    <li class="breadcrumb-item"><a href="{% url 'product-home' %}">Product</a></li>
    <li class="breadcrumb-item"><a active href="#">Delete Product</a></li>
</ol>
{% endblock %}

{% block content %}

<div class="content-container">
  <form action="" method="POST">{%csrf_token%}
    <h3>Delete the following Product?</h3>
    <ul>
    {% for cust in delProducts %}
      <li class=" mt-2"><span class="mr-2">&cross;</span>{{ cust }}</li>
    {% endfor %}
    </ul>
    <button type="submit" name="button" class="button button-delete"><span>Confirm Delete</span></button>
    <a class="ml-3" href="{% url 'product-home' %}">No, Cancel</a>
  </form>
</div>

{% endblock %}

templates/product/product_create.html
{% extends "_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/apps/apps_create_update.css' %}">
<link rel="stylesheet" href="{% static 'css/base/button.css' %}">
<link rel="stylesheet" href="{% static 'css/base/message.css' %}">
{% endblock %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
    {% if perms.customers.is_superuser  %}
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    {% else %}
      <li class="breadcrumb-item">Home</li>
    {% endif %}
    <li class="breadcrumb-item"><a href="{% url 'product-home' %}">Product</a></li>
    <li class="breadcrumb-item"><a active href="#">Add Product</a></li>
</ol>
{% endblock %}

{% block content %}
{% include "_modal.html" %}
<div class="content-container">
	<form method='POST' enctype="multipart/form-data" novalidate id="product-form">{% csrf_token %}
		{{form.productCode | as_crispy_field}}
		{{form.serialNo | as_crispy_field }}
		{{form.category | as_crispy_field }}
		<div class="category-field">
			<a href="{% url 'category_create' %}" id="add_category" onclick="return showAddPopup(this);"><img src="{% static 'images/category-add.png' %}"></a>
			<a id="edit_category"><img src="{% static 'images/category-edit.png' %}"></a>
			<a id="delete_category"><img src="{% static 'images/batch_delete.png' %}" class="mr-3" alt=""></a>
		</div>
		{{form.distributor | as_crispy_field }}
		{{form.description | as_crispy_field }}
		{{form.pricePerUnit | as_crispy_field }}
		{{form.srp | as_crispy_field }}
		<button type="submit" name="button" class="button"><span>Submit</span></button>
	</form>
</div>

{% endblock %}

{% block javascript %}

<script type="text/javascript">
	var kaliwa = (screen.width - 300) / 2;
	var taas = (screen.height - 300) / 2;

	function showEditPopup(url) {
		var win = window.open(url, "Edit", 'height=300, width=300,top=' + taas + ',left=' + kaliwa + '');
		return false;
	}

	function showDeletePopup(url) {
		var win = window.open(url, "Delete", 'height=300, width=300,top=' + taas + ',left=' + kaliwa + '');
		return false;
	}

	function showAddPopup(triggeringLink) {
		var name = triggeringLink.id.replace(/^add_/, '');
		href = triggeringLink.href;
		var win = window.open(href, name, 'height=300, width=300,top=' + taas + ',left=' + kaliwa + '');
		win.focus();
		return false;
	}

	function closeAddPopup(win, newID, newRepr, id) {
		$(id).append('<option value=' + newID + ' selected >' + newRepr + '</option>')
		win.close();
	}

	function closeEditPopup(win, newID, newRepr, oldname, id) {
		$('#id_category option:contains(' + oldname + ')').text(newRepr);
		win.close();
	}

	function closeDeletePopup(win, newID) {
		$("#id_category option[value=" + newID + "]").remove();
		win.close();
	}

	$("a.batch_delete").on("click", function() {
		context = context.toString();
		var url = "{% url 'distributor-delete-batch' 'test' %}";
		url = url.replace('test', context);
		$(this).attr("href", url);
	});
</script>

<script>
	$("#edit_category").click(function() {
		category_name = $("#id_category option:selected").text();
		var data = {
			"category_name": category_name
		};
		$.ajax({
			type: 'GET',
			url: '/product/category/ajax/get_category_id',
			data: data,
			success: function(data) {
				var url = "/product/category/" + data['category_id'] + "/edit/";
				showEditPopup(url);
			},
			error: function(data) {
				alert("No product selected.");
			}
		});
	});


	$("#delete_category").click(function() {
		category_name = $("#id_category option:selected").text();
		var data = {
			"category_name": category_name
		};
		$.ajax({
			type: 'GET',
			url: '/product/category/ajax/get_category_id',
			data: data,
			success: function(data) {
				var url = "/product/category/" + data['category_id'] + "/delete/";
				showDeletePopup(url);
			},
			error: function(data) {
				alert("No product selected.");
			}
		});
	})
</script>

<script>
	$('#div_id_category div').append($('div.category-field'))
	$('#div_id_category div').css('display', 'flex')
	$('#div_id_category div').css('align-items', 'center')
</script>

{% endblock %}

templates/product/product_home.html
{% extends "_base.html" %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/apps/apps_home.css' %}">
<link rel="stylesheet" href="{% static 'css/base/tooltip.css' %}">
{% endblock %}

{% block title %}Products{% endblock %}
{% block breadcrumb_content %}
<ol class="breadcrumb">
    {% if perms.customers.is_superuser  %}
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    {% else %}
      <li class="breadcrumb-item">Home</li>
    {% endif %}
    <li class="breadcrumb-item"><a active href="#">Product</a></li>
</ol>
{% endblock %}
{% block content %}
{% include "_modal.html" %}

<div class="content-container">

  <div class="option-list">
    <div class="option-left">
      <a href="#" id="filter"><img src="{% static 'images/filter.png' %}" alt=""></a>
      <div class="filter-group">
        <div class="filter-container">
          <div class="filter-div">
            <label for="">Category</label>
            <select name="" id="category_list" class="form-control">
              <option value="" selected></option>
              {% for category in category_list %}
                <option value={{category}}>{{category}}</option>
              {% endfor %}
            </select>
          </div>

          <div class="filter-div">
            <label for="">Distributor: </label>
            <select name="" id="distributor_list" class="form-control">
              <option value="" selected></option>
              {% for distri in distributor_list %}
                <option value={{distri}}>{{distri}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
      </div>
    </div>
    <div class="option-right">
      <div class="btn-group">
        {% if products %}
        {% if perms.products.delete_product  or perms.products.export_product %}
        <button type="button" class="crud actions"><img src="{% static 'images/action.png' %}" class="mr-2">Actions</button>
        <button type="button" class="crud actions dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% endif %}
        {% endif %}
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">
          <form action="" method="POST" id="batch_action">
            {% if perms.products.delete_product  %}
            <a class="dropdown-item mb-2 batch_delete" href="#"><img src="{% static 'images/batch_delete.png' %}" class="mr-2">Delete Selected</a>
            {% endif %}
            {% if perms.products.export_product  %}
            <a class="dropdown-item mb-2 batch_export" href="#"><img src="{% static 'images/batch_export.png' %}" class="mr-2">Export Selected</a>
            {% endif %}
          </form>
        </div>
      </div>
      {% if perms.products.add_product  %}
      <a class="crud add-item" href="{% url 'product-create' %}"><img src="{% static 'images/add-product.png' %}" class="mr-2">Add Product</a>
      {% endif %}
      {% if products %}
      {% if perms.products.export_product  %}
      <a class="crud export-all" href="{% url 'product-export' %}"><img src="{% static 'images/excel.png' %}" class="mr-2">Export All</a>
      {% endif %}
      {% if perms.products.delete_product  %}
      <a class="crud delete-all" href="{% url 'product-delete-all' %}"><img src="{% static 'images/delete-all.png' %}" class="mr-2">Delete All</a>
      {% endif %}
      {% endif %}
    </div>

  </div>

  <form action="" id="frm-table" method="post">
  <table id="myTable" class="order-column table table-bordered">
    <thead>
      <tr>
        <th><input type="checkbox" name="select_all" value="1" id="example-select-all"></th>
        <th class="sort">Product Code</th>
        <th class="sort">Serial No.</th>
        <th class="sort">Category</th>
        <th class="sort">Distributor</th>
        <th class="sort">Price/Unit</th>
        <th class="sort">SRP</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
      <tr class="mydata-row">
        <td class="input-td" id="customer-id" value="{{product.pk}}">{{product.pk}}</td>
        <td>
          <div class="tooltips">
            <button type="button" class="button-plain read-data" data-id="{% url 'product-read' product.pk %}">
              {{ product.productCode }}
            </button>
            <div class="top"><p>See more details</p><i></i></div>
          </div>
        </td>
        <td>{{ product.serialNo }}</td>
        <td>{{ product.category }}</td>
        <td>{{ product.distributor }}</td>
        <td class="price-per-unit">{{ product.pricePerUnit }}</td>
        <td class="srp">{{ product.srp }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</form>
  {% if perms.products.change_product or perms.products.delete_product%}
  <ul class='custom-menu'>
    {% if perms.products.change_product  %}
    <li><a class="menu-update"><img src="{% static 'images/edit.png' %}" class="mr-2" alt="">Update</a></li>
    {% endif %}
    {% if perms.products.delete_product %}
    <li><a class="menu-delete"><img src="{% static 'images/delete.png' %}" class="mr-3" alt="">Delete</a></li>
    {% endif %}
  </ul>
  {% endif %}
</div>
{% endblock content %}

{% block javascript %}
<script type="text/javascript" src="{% static 'dataTables/datatables.min.js' %}"></script>
<script src="{% static 'assets/js/dataTables.checkboxes.js' %}" charset="utf-8"></script>
<script src="{% static 'js/apps/modalview.js' %}" charset="utf-8"></script>
<script src="{% static 'js/apps/rightclick_menu.js' %}" charset="utf-8"></script>
<script src="{% static 'js/apps/loadTable.js' %}" charset="utf-8"></script>

<!-- THIS IS FOR BATCH FUNCTION BUTTONS -->
<script>

  var selected_items;
  $(document).ready(function() {

	  $('a#filter').on("click", function(){
      if ($('.filter-group').is(":visible")){
        $('.filter-group').hide(100);
      }
      else{
        $('.filter-group').show(100);
      }
    });

    // BATCH EXPORT
    $("a.batch_export").on("click", function() {
      getSelectedItems();
      if(selected_items == ""){
        alert("Please select an item first.")
      }
      else{
        var url = "{% url 'product-export_batch' 'test' %}";
        url = url.replace('test', selected_items);
        $(this).attr("href", url);
      }
    });

    // BATCH DELETE
    $("a.batch_delete").on("click", function() {
      getSelectedItems();
      if(selected_items == ""){
        alert("Please select an item first.")
      }
      else{
        var url = "{% url 'product-delete-batch' 'test' %}";
        url = url.replace('test', selected_items);
        $(this).attr("href", url);
      }
    });

    // UPDATE ITEM
    $("a.menu-update").on("click", function() {
      var url = "{% url 'product-update' 'test' %}";
      url = url.replace('test', id);
      $(this).attr("href", url);
    });

    // DELETE ITEM
    $("a.menu-delete").on("click", function() {
      var url1 = "{% url 'product-delete-batch' 'test' %}";
      url1 = url1.replace('test', id);
      $(this).attr("href", url1);
    });
  });

</script>
{% endblock %}

templates/product/product_update.html
{% extends "product/product_create.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block breadcrumb_content %}
<ol class="breadcrumb">
    {% if perms.customers.is_superuser  %}
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    {% else %}
      <li class="breadcrumb-item">Home</li>
    {% endif %}
    <li class="breadcrumb-item"><a href="{% url 'product-home' %}">Product</a></li>
    <li class="breadcrumb-item"><a active href="#">Update Product</a></li>
</ol>
{% endblock %}