myapp/urls.py
from django.urls import path
from .views import HomePageView


urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

salesforce_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import ProfilePageView

admin.site.site_header = "Salesforce Admin Page"
admin.site.site_title = "Salesforce Management System portal"
admin.site.index_title = "Welcome to Salesforce admin page!"



urlpatterns = [
    path('admin/', admin.site.urls, name='admin-pages'),
    path('profile/<int:pk>', ProfilePageView.as_view(), name='profile'),


    # User management
    path('', include('dashboards.urls')),
    path('dashboard/', include('dashboards.urls')),
    path('accounts/', include('allauth.urls')),
    path('customer/', include('customers.urls')),
    path('distributor/', include('distributors.urls')),
    path('product/', include('products.urls')),
    path('estimate/', include('estimates.urls')),

]

handler404 = 'myapp.views.my_custom_page_not_found_view'
handler500 = 'myapp.views.my_custom_error_view'
handler400 = 'myapp.views.my_custom_bad_request_view'

customers/models.py
from django.db import models
from django.urls import reverse
import datetime
from django.contrib.auth import get_user_model

now = datetime.datetime.now()

class Customer(models.Model):
    companyName = models.CharField(max_length=100, unique=True)
    email = models.EmailField()
    phone = models.CharField(max_length=12)
    phone2 = models.CharField(max_length=12, blank=True)
    contactPerson = models.CharField(max_length=50)
    contactPerson2 = models.CharField(max_length=50, blank=True)
    addressLine1 = models.CharField(max_length=100)
    addressLine2 = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    postalCode = models.CharField(max_length=10)
    country = models.CharField(max_length=50)
    website = models.CharField(max_length=100, blank=True)
    additionalInfo = models.TextField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='customer_created')
    last_updated_at = models.DateTimeField(auto_now=True)
    last_updated_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='customer_updated')

    class Meta:
        permissions = [
            ('export_customer', 'Can export customer data as excel file'),
        ]

    def __str__(self):
        return self.companyName

    def get_absolute_url(self):
        return reverse('customer-home')

estimates/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

# IMPORT MODELS
from products.models import Product
from customers.models import Customer
from distributors.models import Distributor

import datetime
STATUS_CHOICES = [
    ('Pending', 'Pending'),
    ('Cancelled', 'Cancelled'),
    ('Successful', 'Successful'),
]
now = datetime.datetime.now()

class Markup(models.Model):
    markup = models.PositiveIntegerField()

    def __str__(self):
        return str(self.markup)

class Estimate(models.Model):
    estimateNumber = models.CharField(max_length=200)
    projectName = models.CharField(max_length=200)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, related_name='estimate_customer')
    overallInvestment = models.DecimalField(max_digits=20, decimal_places=2)
    overallNonTax = models.DecimalField(max_digits=20, decimal_places=2)
    overallTaxPerLot = models.DecimalField(max_digits=20, decimal_places=2)
    overallWithTaxPerUnit = models.DecimalField(max_digits=20, decimal_places=2)
    overallWithTax = models.DecimalField(max_digits=20, decimal_places=2)
    overallProfit = models.DecimalField(max_digits=20, decimal_places=2)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, blank=True, default='Pending')
    quotationNotes = models.TextField(max_length=500, blank=True)
    invoiceNotes = models.TextField(max_length=500, blank=True)
    poNotes = models.TextField(max_length=500, blank=True)
    modeOfPayment = models.PositiveIntegerField()
    nonVatLabel = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='estimate_created')
    last_updated_at = models.DateTimeField(auto_now=True)
    last_updated_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='estimate_updated')
    completedDate = models.DateField(auto_now=False, null=True, blank = True)

    def __str__(self):
        return self.estimateNumber

    def get_absolute_url(self):
        return reverse('estimate-home')

    class Meta:
        permissions = [
            ('export_estimate', 'Can export estimate data as excel file'),
        ]

class ProductProfit(models.Model):
    estimateNumber = models.CharField(max_length=200)
    productCode = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name='productprofit_productcode')
    serialNo = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    distributor = models.ForeignKey(Distributor, on_delete=models.SET_NULL, null=True, related_name='productprofit_distributor')
    pricePerUnit = models.DecimalField(max_digits=20, decimal_places=2)
    delivered = models.CharField(max_length=20, blank=True, default='No')
    qty = models.PositiveIntegerField()
    markup = models.PositiveIntegerField()
    totalInvestment = models.DecimalField(max_digits=20, decimal_places=2)
    srp = models.DecimalField(max_digits=20, decimal_places=2)
    newSRPPerUnit = models.DecimalField(max_digits=20, decimal_places=2)
    totalNonTax = models.DecimalField(max_digits=20, decimal_places=2)
    taxPerUnit = models.DecimalField(max_digits=20, decimal_places=2)
    totalTaxPerLot = models.DecimalField(max_digits=20, decimal_places=2)
    totalWithTaxPerUnit = models.DecimalField(max_digits=20, decimal_places=2)
    totalWithTax = models.DecimalField(max_digits=20, decimal_places=2)
    profit = models.DecimalField(max_digits=20, decimal_places=2)

    def __str__(self):
        return str(self.productCode)

    def get_absolute_url(self):
        return reverse('estimates:estimate-home')

products/models.py
from django.db import models
from distributors.models import Distributor
from django.contrib.auth import get_user_model
from django.urls import reverse
import datetime
now = datetime.datetime.now()

class Category(models.Model):
    categoryname = models.CharField(max_length=100)

    def __str__(self):
        return self.categoryname

class Product(models.Model):
    productCode = models.CharField(max_length=100, unique=True)
    serialNo = models.CharField(max_length=100, unique=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='product_category')
    description = models.CharField(max_length=100)
    distributor = models.ForeignKey(Distributor, on_delete=models.SET_NULL, null=True, related_name='product_distributor')
    pricePerUnit = models.DecimalField(max_digits=10, decimal_places=2)
    srp = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='product_created')
    last_updated_at = models.DateTimeField(auto_now=True)
    last_updated_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='product_updated')

    class Meta:
        permissions = [
            ('export_product', 'Can export product data as excel file'),
        ]

    def __str__(self):
        return self.productCode

    def get_absolute_url(self):
        return reverse('product-home')

templates/_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>{% block title %}AvantGarde Technologies - Salesforce Management System{% endblock title %}</title>

  <link rel="stylesheet" href="{% static 'css/base/css-reset.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.theme.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/base/button.css' %}">
  <link rel="stylesheet" href="{% static 'css/base/_base.css' %}">

  <!-- DATA TABLES -->
  <link rel="stylesheet" href="{% static 'dataTables/datatables.css' %}">
  <link rel="stylesheet" href="{% static 'dataTables/semantic.min.css' %}">

  {% block extrahead %}
  {% endblock extrahead %}

</head>

<body>
  <div id="container">
    <nav class="breadcrumb-nav" aria-label="breadcrumb">
      {% block breadcrumb_content %}
      {% endblock %}
    </nav>
    <div class="main-header" id="header">
      <div class="company-name">
        <p>AvantGarde Technologies</p>
      </div>
      <div class="navigation-tabs">
        {% if perms.customers.is_superuser  %}
        <a class="navbutton" href="{% url 'home' %}">DASHBOARD</a>
        {% else %}
        {% endif %}
        {% if perms.customers.view_customer  %}
        <a class="navbutton" href="{% url 'customer-home' %}">CUSTOMERS</a>
        {% endif %}
        {% if perms.distributors.view_distributor  %}
        <a class="navbutton" active href="{% url 'distributor-home' %}">DISTRIBUTORS</a>
        {% endif %}
        {% if perms.products.view_product  %}
        <a class="navbutton" href="{% url 'product-home' %}">PRODUCTS</a>
        {% endif %}
        {% if perms.estimates.view_estimate %}
        <a class="navbutton" href="{% url 'estimate-home' %}">ESTIMATES</a>
        {% endif %}
      </div>
      <div class="account-profile">
        {% if user.is_authenticated %}
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> {{ user.username }} </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-profile" aria-labelledby="userMenu" >
              <a class="dropdown-item" href="{% url 'profile' user.pk %}">View Profile</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account_change_password' %}">Change Password</a>
              <div class="dropdown-divider"></div>
              {% if request.user.is_staff %}
              <a class="dropdown-item" href="{% url 'admin:index' %}">Accounts and Permissions</a>
              <div class="dropdown-divider"></div>
              {% endif %}
              <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
            </div>
          </li>
        </ul>
      {% endif %}
      </div>

    </div>

    <div class="main-container">
      {% if messages %}
      {% for message in messages %}
      <div class="popup-message">
        <h3>{{message}}</h3>
      </div>

      {% endfor %}
      {% endif %}
      {% block content %}

        <div class="home-container">
          <div class="welcome-container text-center">
            <h1 class="welcome-company-name"><img class="wave-image" src="{% static 'images/wave.png' %}" alt="">Welcome {{user.username}}!</h1>
            <h3>AvantGarde Technologies Salesforce Management System</h3>
            <input class="jscolor {onFineChange:'update(this)'}" value="cc66ff">

          </div>
        </div>
      {% endblock %}
    </div>

  </div>

  <!-- JQUEERY LIBRARY -->
  <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
  <script src="{% static 'assets/js/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
  <script src="{% static 'js/jscolor.js'%}" charset="utf-8"></script>
  <script>
    $(".popup-message").fadeTo(2000, 500).slideUp(500, function() {
        $(this).slideUp(500);
    });
    function update(jscolor) {
    // 'jscolor' instance can be used as a string
      document.getElementById('header').style.backgroundColor = '#' + jscolor;
    }
  </script>

  {% block javascript %}

  {% endblock javascript%}

</body>

</html>

templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

templates/profile.html
{% extends "_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extrahead %}
  <link rel="stylesheet" href="{% static 'css/accounts/profile.css' %}">
  <link rel="stylesheet" href="{% static 'css/base/button.css' %}">
{% endblock extrahead %}
{% block breadcrumb_content %}
<ol class="breadcrumb">
    {% if perms.customers.is_superuser  %}
      <li class="breadcrumb-item"><a href="{% url 'dashboard-home' %}">Home</a></li>
    {% else %}
      <li class="breadcrumb-item">Home</li>
    {% endif %}
    <li class="breadcrumb-item"><a active href="#">Update Profile</a></li>
</ol>
{% endblock %}
{% block content %}
<div class="content-container">
  <form method="POST">{% csrf_token %}
      {{ form | crispy }}
      <button type="submit" class="button"><span>Save</span></button>
  </form>
</div>
{% endblock content %}