estimates/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (view_estimate, create_estimate, estimate_homeview,
                    estimate_edit, estimate_duplicate,
                    export_estimates,export_estimates_single,export_estimates_batch,
                    batch_delete_estimates, delete_all_estimates,)
from . import views


urlpatterns = [
    path('', estimate_homeview, name='estimate-home'),
    path('create/', create_estimate, name='estimate-create'),
    path('<id>/view', view_estimate, name='estimate-read'),
    path('<pk>/update/', estimate_edit, name='estimate-update'),
    path('<pk>/duplicate/', estimate_duplicate, name='estimate-duplicate'),

    path('ajax/validate_productCode', views.validate_product, name='validate_productCode'),
    path('ajax/validate_customer', views.validate_customer, name='validate_customer'),

    path('export/csv/', export_estimates, name='estimate-export'),
    path('<id>/export/csv/single', export_estimates_single, name='estimate-export-single'),
    path('<str:id>/export/csv/batch', export_estimates_batch, name='estimate-export_batch'),

    path('<str:id>/delete', batch_delete_estimates, name='estimate-delete-batch'),
    path('delete/', delete_all_estimates, name='estimate-delete-all'),


]

myapp/urls.py
from django.urls import path
from .views import HomePageView


urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

salesforce_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import ProfilePageView

admin.site.site_header = "Salesforce Admin Page"
admin.site.site_title = "Salesforce Management System portal"
admin.site.index_title = "Welcome to Salesforce admin page!"



urlpatterns = [
    path('admin/', admin.site.urls, name='admin-pages'),
    path('profile/<int:pk>', ProfilePageView.as_view(), name='profile'),


    # User management
    path('', include('dashboards.urls')),
    path('dashboard/', include('dashboards.urls')),
    path('accounts/', include('allauth.urls')),
    path('customer/', include('customers.urls')),
    path('distributor/', include('distributors.urls')),
    path('product/', include('products.urls')),
    path('estimate/', include('estimates.urls')),

]

handler404 = 'myapp.views.my_custom_page_not_found_view'
handler500 = 'myapp.views.my_custom_error_view'
handler400 = 'myapp.views.my_custom_bad_request_view'

estimates/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

# IMPORT MODELS
from products.models import Product
from customers.models import Customer
from distributors.models import Distributor

import datetime
STATUS_CHOICES = [
    ('Pending', 'Pending'),
    ('Cancelled', 'Cancelled'),
    ('Successful', 'Successful'),
]
now = datetime.datetime.now()

class Markup(models.Model):
    markup = models.PositiveIntegerField()

    def __str__(self):
        return str(self.markup)

class Estimate(models.Model):
    estimateNumber = models.CharField(max_length=200)
    projectName = models.CharField(max_length=200)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, related_name='estimate_customer')
    overallInvestment = models.DecimalField(max_digits=20, decimal_places=2)
    overallNonTax = models.DecimalField(max_digits=20, decimal_places=2)
    overallTaxPerLot = models.DecimalField(max_digits=20, decimal_places=2)
    overallWithTaxPerUnit = models.DecimalField(max_digits=20, decimal_places=2)
    overallWithTax = models.DecimalField(max_digits=20, decimal_places=2)
    overallProfit = models.DecimalField(max_digits=20, decimal_places=2)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, blank=True, default='Pending')
    quotationNotes = models.TextField(max_length=500, blank=True)
    invoiceNotes = models.TextField(max_length=500, blank=True)
    poNotes = models.TextField(max_length=500, blank=True)
    modeOfPayment = models.PositiveIntegerField()
    nonVatLabel = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='estimate_created')
    last_updated_at = models.DateTimeField(auto_now=True)
    last_updated_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='estimate_updated')
    completedDate = models.DateField(auto_now=False, null=True, blank = True)

    def __str__(self):
        return self.estimateNumber

    def get_absolute_url(self):
        return reverse('estimate-home')

    class Meta:
        permissions = [
            ('export_estimate', 'Can export estimate data as excel file'),
        ]

class ProductProfit(models.Model):
    estimateNumber = models.CharField(max_length=200)
    productCode = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name='productprofit_productcode')
    serialNo = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    distributor = models.ForeignKey(Distributor, on_delete=models.SET_NULL, null=True, related_name='productprofit_distributor')
    pricePerUnit = models.DecimalField(max_digits=20, decimal_places=2)
    delivered = models.CharField(max_length=20, blank=True, default='No')
    qty = models.PositiveIntegerField()
    markup = models.PositiveIntegerField()
    totalInvestment = models.DecimalField(max_digits=20, decimal_places=2)
    srp = models.DecimalField(max_digits=20, decimal_places=2)
    newSRPPerUnit = models.DecimalField(max_digits=20, decimal_places=2)
    totalNonTax = models.DecimalField(max_digits=20, decimal_places=2)
    taxPerUnit = models.DecimalField(max_digits=20, decimal_places=2)
    totalTaxPerLot = models.DecimalField(max_digits=20, decimal_places=2)
    totalWithTaxPerUnit = models.DecimalField(max_digits=20, decimal_places=2)
    totalWithTax = models.DecimalField(max_digits=20, decimal_places=2)
    profit = models.DecimalField(max_digits=20, decimal_places=2)

    def __str__(self):
        return str(self.productCode)

    def get_absolute_url(self):
        return reverse('estimates:estimate-home')

estimates/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse_lazy, reverse

# DECORATORS
from django.contrib.auth.decorators import permission_required, login_required
from django.views.decorators.csrf import csrf_exempt

# BOOTSTRAP forms
from bootstrap_modal_forms.generic import BSModalReadView

# MIXINS
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

# IMPORT TEMPLATE VIEWS
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

# IMPORT MODELS
from .models import Estimate, ProductProfit
from products.models import Product
from customers.models import Customer
from distributors.models import Distributor
from django.contrib.auth.models import User
from django.db.models import Q

# IMPORT FORMS
from .forms import ProductProfitModelForm, ProductProfitModelFormset, EstimateModelForm, ProductProfitModelFormset2, MarkupForm

from django.shortcuts import get_object_or_404

import json
import datetime
from datetime import date
import csv


class EstimateListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Estimate
    template_name = 'estimate/estimate_home.html'
    context_object_name = 'estimates'
    ordering = ['estimateNumber']

    permission_required = 'estimates.view_estimate'

@login_required
@permission_required('estimates.view_estimate', raise_exception=True)
def estimate_homeview(request):
    template_name = 'estimate/estimate_home.html'
    context = {}
    customerList = set()
    statusList = set()

    estimate = Estimate.objects.all()

    for est in estimate:
        customerList.add(est.customer)

    for est in estimate:
        statusList.add(est.status)

    context['estimates'] = estimate
    context['customer_list'] = customerList
    context['status_list'] = statusList

    return render(request, template_name, context)

# CREATE ESTIMATE FUNCTION VIEW
@login_required
@permission_required('estimates.add_estimate', raise_exception=True)
def create_estimate(request):

    # CODES FOR GENERATING ESTIMATE NUMBER
    today = datetime.datetime.now()
    nowYear = today.strftime('%Y')
    last_estimate = Estimate.objects.all().order_by('id').last()

    if(last_estimate):
        estimateNumber = last_estimate.estimateNumber
        currYear = estimateNumber[:4]
        currEstimateNumber = int(estimateNumber[5:])
        newEstimateNumber = currEstimateNumber + 1
        formattedEstimateNumber = str(newEstimateNumber)
        formattedEstimateNumber = formattedEstimateNumber.zfill(5)

        if(currYear == nowYear):
            newYear = currYear
        else:
            newYear = nowYear

        newNumber = newYear + "-" + formattedEstimateNumber
    else:
        newNumber = nowYear + '-00100'

    template_name = 'estimate/create_estimate.html'

    if request.method == 'GET':
        formset = ProductProfitModelFormset(queryset=ProductProfit.objects.none())
        estimateform = EstimateModelForm(request.GET or None)

    elif request.method == 'POST':
        estimateform = EstimateModelForm(request.POST)
        formset = ProductProfitModelFormset(request.POST)
        print('It is a form request');
        if estimateform.is_valid() and formset.is_valid():
            estimateInstance = estimateform.save(commit=False)
            estimateInstance.created_by = request.user
            estimateInstance.last_updated_by = request.user
            estimateInstance.delivered = "No"
            estimateform.save()

            for form in formset:
                if form.is_valid():
                    instance = form.save(commit=False)
                    if (instance.pricePerUnit != None):
                        instance.estimateNumber = newNumber
                        instance.status = 'Pending'
                        instance.save()

            return redirect('/estimate')
        else:
            print("hahaha")
            print(estimateform.errors)

    return render(request, template_name, {
        'formset': formset,
        'estimateform': estimateform,
        'estimateNumber': newNumber,
    })


# FUNCTION BASED VIEW TO CHECK ESTIMATES "DETAIL VIEW"
@login_required
@permission_required('estimates.view_estimate', raise_exception=True)
def view_estimate(request, id):

    # ADD A DICTIONARY
    context ={}

    # GET SPECIFIC OBJECT TO A DICTIONARY
    myEstimate = Estimate.objects.get(pk = id)

    # ADD SPECIFIC OBJECT TO A DICTIONARY
    context['estimate'] = myEstimate
    distriList = set()
    myEstimateNumber = myEstimate.estimateNumber

    # GET ALL PRODUCTS RELATED TO THE ESTIMATE NUMBER
    myprods = ProductProfit.objects.filter(estimateNumber=myEstimateNumber)

    for prod in myprods:
        distriList.add(prod.distributor)


    context['product_list'] = myprods
    context['distributor_list'] = distriList

    return render(request, "estimate/view_estimate.html", context)

@login_required
@permission_required('estimates.add_estimate', raise_exception=True)
def estimate_duplicate(request, pk):

    # CODES FOR GENERATING ESTIMATE NUMBER
    today = datetime.datetime.now()
    nowYear = today.strftime('%Y')
    last_estimate = Estimate.objects.all().order_by('id').last()

    if(last_estimate):
        estimateNumber = last_estimate.estimateNumber
        currYear = estimateNumber[:4]
        currEstimateNumber = int(estimateNumber[5:])
        newEstimateNumber = currEstimateNumber + 1
        formattedEstimateNumber = str(newEstimateNumber)
        formattedEstimateNumber = formattedEstimateNumber.zfill(5)

        if(currYear == nowYear):
            newYear = currYear
        else:
            newYear = nowYear

        newNumber = newYear + "-" + formattedEstimateNumber
    else:
        newNumber = nowYear + '-00100'

    template_name = 'estimate/create_estimate.html'

    context ={}
    myEstimate = get_object_or_404(Estimate, pk=pk)

    estimateForm = EstimateModelForm(request.POST or None, instance=myEstimate)
    formsets = ProductProfitModelFormset(request.POST or None, queryset=ProductProfit.objects.filter(estimateNumber=myEstimate.estimateNumber))

    context["estimateNumber"] = newNumber
    context["estimateform"] = estimateForm
    context["formset"] = formsets

    if request.method == 'GET':
        formset = ProductProfitModelFormset(queryset=ProductProfit.objects.none())
        estimateform = EstimateModelForm(request.GET or None)

    elif request.method == 'POST':
        estimateform = EstimateModelForm(request.POST)
        formset = ProductProfitModelFormset(request.POST)
        if estimateform.is_valid() and formset.is_valid():
            print('estimate is valid');
            estimateInstance = estimateform.save(commit=False)
            estimateInstance.created_by = request.user
            estimateInstance.last_updated_by = request.user
            estimateform.save()

            for form in formset:
                if form.is_valid():
                    instance = form.save(commit=False)
                    if (instance.pricePerUnit != None):
                        instance.estimateNumber = newNumber
                        instance.status = 'Pending'
                        instance.save()
                else:
                    print("formset here=====")
                    print(form.errors)
            return redirect('/estimate')
        else:
            print("hahaha")
            print(estimateform.errors)

    return render(request, template_name, context)


# CHECK IF PRODUCT IS EXISTING AND FILL OUT DETAILS IF IT EXIST
def validate_product(request):
    productCode = request.GET.get('productCode', None)
    distrikey = Product.objects.values_list('distributor', flat=True).get(productCode=productCode)
    data = {
        'is_taken': Product.objects.filter(productCode__iexact=productCode).exists(),
        'description': Product.objects.values_list('description', flat=True).get(productCode=productCode),
        'serialNo': Product.objects.values_list('serialNo', flat=True).get(productCode=productCode),
        'distributor': Distributor.objects.values_list('distributorName', flat=True).get(pk=distrikey),
        'priceperunit': Product.objects.values_list('pricePerUnit', flat=True).get(productCode=productCode),
        'srp': Product.objects.values_list('srp', flat=True).get(productCode=productCode),
        'distributorID': distrikey
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this username already exists.'
    return JsonResponse(data)

# CHECK IF CUSTOMER IS EXISTING AND FILL OUT DETAILS IF IT EXIST
def validate_customer(request):
    companyName = request.GET.get('companyName', None)
    data = {
        'is_taken': Customer.objects.filter(companyName__iexact=companyName).exists(),
        'addressLine1': Customer.objects.values_list('addressLine1', flat=True).get(companyName=companyName),
        'addressLine2': Customer.objects.values_list('addressLine2', flat=True).get(companyName=companyName),
        'city': Customer.objects.values_list('city', flat=True).get(companyName=companyName),
        'postalCode': Customer.objects.values_list('postalCode', flat=True).get(companyName=companyName),
        'country': Customer.objects.values_list('country', flat=True).get(companyName=companyName),
    }
    if data['is_taken']:
        data['error_message'] = 'A customer with this username already exists.'
    return JsonResponse(data)

# ############################################################# #

@login_required
@permission_required('estimates.export_estimate', raise_exception=True)
def export_estimates(request):
    now = datetime.datetime.now()
    response = HttpResponse(content_type='text/csv')
    filename = 'attachment; filename=' + 'Estimate - ' + \

templates/estimate/estimate_batch_delete.html
{% extends "_base.html" %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/apps/apps_create_update.css' %}">
{% endblock %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
    {% if perms.customers.is_superuser  %}
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    {% else %}
      <li class="breadcrumb-item">Home</li>
    {% endif %}
    <li class="breadcrumb-item"><a href="{% url 'estimate-home' %}">Estimate</a></li>
    <li class="breadcrumb-item"><a active href="#">Delete Estimate</a></li>
</ol>
{% endblock %}

{% block content %}

<div class="content-container">
  <form action="" method="POST">{%csrf_token%}
    <h3>Delete the following Estimate?</h3>
    <ul>
    {% for cust in delEstimates %}
      <li class=" mt-2"><span class="mr-2">&cross;</span>{{ cust }}</li>
    {% endfor %}
    </ul>
    <button type="submit" name="button" class="button button-delete"><span>Confirm Delete</span></button>
    <a class="ml-3" href="{% url 'estimate-home' %}">No, Cancel</a>
  </form>
</div>

{% endblock %}

templates/estimate/estimate_home.html
{% extends "_base.html" %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/apps/apps_home.css' %}">
<link rel="stylesheet" href="{% static 'css/base/tooltip.css' %}">
{% endblock %}

{% block title %}Estimates{% endblock %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
    {% if perms.customers.is_superuser  %}
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    {% else %}
      <li class="breadcrumb-item">Home</li>
    {% endif %}
    <li class="breadcrumb-item"><a active href="#">Estimate</a></li>
</ol>
{% endblock %}

{% block content %}
{% include "_modal.html" %}

<div class="content-container">

  <div class="option-list">
    <div class="option-left">
      <a href="#" id="filter"><img src="{% static 'images/filter.png' %}" alt=""></a>
      <div class="filter-group">
        <div class="filter-container">

          <div class="filter-div">
            <label for="">Customer: </label>
            <select name="" id="customer_list" class="form-control">
              <option value="" selected></option>
              {% for customer in customer_list %}
                <option value={{customer}}>{{customer}}</option>
              {% endfor %}
            </select>
          </div>

          <div class="filter-div">
            <label for="">Status: </label>
            <select name="" id="status_list" class="form-control">
              <option value="" selected></option>
              {% for status in status_list %}
                <option value={{status}}>{{status}}</option>
              {% endfor %}
            </select>
          </div>

          <div class="filter-div">
            <label for="">From: </label>
            <input class="form-control"  type="text" id="min">
          </div>

          <div class="filter-div">
            <label for="">To: </label>
            <input class="form-control" type="text" id="max">
          </div>

        </div>
      </div>
    </div>
    <div class="option-right">
      <div class="btn-group">
        {% if estimates %}
        {% if perms.estimates.delete_estimate  or perms.estimates.export_estimate %}
        <button type="button" class="crud actions"><img src="{% static 'images/action.png' %}" class="mr-2">Actions</button>
        <button type="button" class="crud actions dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% endif %}
        {% endif %}
        <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">
          <form action="" method="POST" id="batch_action">
            {% if perms.estimates.delete_estimate  %}
            <a class="dropdown-item mb-2 batch_delete" href="#"><img src="{% static 'images/batch_delete.png' %}" class="mr-2">Delete Selected</a>
            {% endif %}
            {% if perms.estimates.export_estimate  %}
            <a class="dropdown-item mb-2 batch_export" href="#"><img src="{% static 'images/batch_export.png' %}" class="mr-2">Export Selected</a>
            {% endif %}
          </form>
        </div>
      </div>
      {% if perms.estimates.add_estimate  %}
      <a class="crud add-item" href="{% url 'estimate-create' %}"><img src="{% static 'images/add-estimate.png' %}" class="mr-2">Add Estimate</a>
      {% endif %}
      {% if estimates %}
      {% if perms.estimates.export_estimate  %}
      <a class="crud export-all" href="{% url 'estimate-export' %}"><img src="{% static 'images/excel.png' %}" class="mr-2">Export All</a>
      {% endif %}
      {% if perms.estimates.delete_estimate  %}
      <a class="crud delete-all" href="{% url 'estimate-delete-all' %}"><img src="{% static 'images/delete-all.png' %}" class="mr-2">Delete All</a>
      {% endif %}
      {% endif %}
    </div>
  </div>

  <form action="" id="frm-table" method="post">
  <table id="myTable" class="order-column table table-bordered">
    <thead>
      <tr>
        <th><input type="checkbox" name="select_all" value="1" id="example-select-all"></th>
        <th class="sort">Estimate Number</th>
        <th class="sort">Project Name</th>
        <th class="sort">Customer</th>
        <th class="sort">Investment</th>
        <th class="sort">Profit</th>
        <th class="sort">Status</th>
        <th class="sort">Date Created</th>
      </tr>
    </thead>
    <tbody>
      {% for estimate in estimates %}
      <tr class="mydata-row">
        <td class="input-td" id="customer-id" value={{estimate.pk}}>{{estimate.pk}}</td>
        <td>
          <div class="tooltips">
            <a class="estimate-link" href="{% url 'estimate-read' estimate.pk %}">{{ estimate.estimateNumber }}</a>
            <div class="top"><p>See more details</p><i></i></div>
          </div>
        </td>
        <td>{{ estimate.projectName }}</td>
        <td>{{ estimate.customer }}</td>
        <td class="investment">{{ estimate.overallInvestment }}</td>
        <td class="profit">{{ estimate.overallProfit }}</td>
        <td>{{ estimate.status }}</td>
        <td>{{ estimate.created_at |date:'m/d/Y'}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  </form>
  {% if perms.estimates.change_estimate or perms.estimates.delete_estimate%}
  <ul class='custom-menu'>
    {% if perms.estimates.change_estimate  %}
    <li><a class="menu-update"><img src="{% static 'images/edit.png' %}" class="mr-2" alt="">Update</a></li>
    {% endif %}
    {% if perms.estimates.delete_estimate %}
    <li><a class="menu-delete"><img src="{% static 'images/delete.png' %}" class="mr-3" alt="">Delete</a></li>
    {% endif %}
    <li><a class="menu-duplicate"><img src="{% static 'images/duplicate.png' %}" class="mr-3" alt="">Duplicate</a></li>
  </ul>
  {% endif %}

</div>
{% endblock content %}

{% block javascript %}
<script type="text/javascript" src="{% static 'dataTables/datatables.min.js' %}"></script>
<script src="{% static 'assets/js/dataTables.checkboxes.js' %}" charset="utf-8"></script>
<script src="{% static 'js/apps/modalview.js' %}" charset="utf-8"></script>
<script src="{% static 'js/apps/rightclick_menu.js' %}" charset="utf-8"></script>
<script src="{% static 'js/apps/date_range.js' %}" charset="utf-8"></script>
<script src="{% static 'js/apps/loadTable.js' %}" charset="utf-8"></script>
<!-- THIS IS FOR BATCH FUNCTION BUTTONS -->
<script>
  var selected_items;
  $(document).ready(function() {

    $('a#filter').on("click", function(){
      if ($('.filter-group').is(":visible")){
        $('.filter-group').hide();
      }
      else{
        $('.filter-group').show();
      }
    });

    $("a.batch_export").on("click", function() {
      getSelectedItems();
      if(selected_items == ""){
        alert("Please select an item first.")
      }
      else{
        var url = "{% url 'estimate-export_batch' 'test' %}";
        url = url.replace('test', selected_items);
        $(this).attr("href", url);
      }
    });

    $("a.batch_delete").on("click", function() {
      getSelectedItems();
      if(selected_items == ""){
        alert("Please select an item first.")
      }
      else{
        var url = "{% url 'estimate-delete-batch' 'test' %}";
        url = url.replace('test', selected_items);
        $(this).attr("href", url);
      }
    });

    $("a.menu-delete").on("click", function() {
      var url1 = "{% url 'estimate-delete-batch' 'test' %}";
      url1 = url1.replace('test', id);
      $(this).attr("href", url1);
    });

    $("a.menu-update").on("click", function() {
      var url = "{% url 'estimate-update' 'test' %}";
      url = url.replace('test', id);
      $(this).attr("href", url);
    });

    $("a.menu-duplicate").on("click", function() {
      var url = "{% url 'estimate-duplicate' 'test' %}";
      url = url.replace('test', id);
      $(this).attr("href", url);
    });
  });
</script>

<script>

</script>

{% endblock %}

templates/estimate/estimate_update.html
{% extends "estimate/create_estimate.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block breadcrumb_content %}
<ol class="breadcrumb">
    {% if perms.customers.is_superuser  %}
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    {% else %}
      <li class="breadcrumb-item">Home</li>
    {% endif %}
    <li class="breadcrumb-item"><a href="{% url 'estimate-home' %}">Estimate</a></li>
    <li class="breadcrumb-item"><a active href="#">Update Estimate</a></li>
</ol>
{% endblock %}

{% block estimateNum %}{{estimateform.estimateNumber}}{% endblock %}
{% block status %}
<div class="input-data">
  <label for="">Status</label>
  {{estimateform.status | as_crispy_field }}
</div>
{% endblock %}